[package]
name = "native"
version = "0.1.0"
authors = ["Ashley Mannix <ashleymannix@live.com.au>"]

[lib]
crate-type = ["cdylib"]

[dependencies]
libc = "*"
slab = "*"
pool = { version = "*", git = "https://github.com/Geal/pool.git" }