[package]
name = "hello_native"
version = "0.0.1"
description = "A library for testing cargo nuget"
authors = ["Ashley Mannix <ashleymannix@live.com.au>"]

[lib]
crate-type = ["dylib"]

[dependencies]
libc = "*"